(use gl)
(use gl.glut)

(define (main args)
  (glut-init args)
  (glut-init-display-mode GLUT_RGBA)
  (glut-create-window "指定された枠の輪郭を描くペインタ")
  (glut-display-func display)
  (init)
  (glut-main-loop)
  )

(define (display)
  (gl-color 1.0 0.0 0.0)
  (gl-begin GL_LINE_LOOP)
  (gl-vertex -0.9 -0.9)
  (gl-vertex 0.9 -0.9)
  (gl-vertex 0.9 0.9)
  (gl-vertex -0.9 0.9)
  (gl-end)
  (gl-flush)
  )

(define (init)
  (gl-clear-color 0.0 0.0 1.0 1.0)
  )
